Documentation:
  Enabled: false
Rails:
  Enabled: true

AllCops:
  Include:
    - '**/*.rb'
    - '**/Rakefile'
    - '**/Gemfile'
    - '**/config.ru'
  Exclude:
    - 'db/**/*'
    - 'Rakefile'
    - 'config/**/*'
    - 'bin/**/*'
    - 'script/**/*'
    - 'spec/rails_helper.rb'
    - 'spec/spec_helper.rb'
    - 'vendor/**/*'
    - 'vendor/**/*.rb'
  UseCache: false
  TargetRailsVersion: 5.1
  TargetRubyVersion: 2.5
Metrics/BlockLength:
  ExcludedMethods: ['describe', 'context', 'feature', 'scenario', 'let']
Style/FrozenStringLiteralComment:
  Enabled: false
