language: ruby
script:
  - bundle exec rspec
  - bundle exec rubocop --config .rubocop.yml
  - bundle-audit check --update
rvm:
  - 2.5.1
services:
  - postgresql
before_script:
  - gem install bundle-audit
  - psql -c 'create database test_travis;' -U postgres
  - cp config/database.yml.travis config/database.yml
